version: '3.4'

services:

  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: src/gateways/API.Gateway/Dockerfile
    container_name: apigateway

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul

  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongo

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672

  medicalservice:
    image: medicalservice:latest
    build:
      context: .
      dockerfile: src/services/MedicalService/Dockerfile
    container_name: medicalservice
    depends_on:
      - mongo
      - rabbitmq

  foodservice:
    image: foodservice:latest
    build:
      context: .
      dockerfile: src/services/FoodService/Dockerfile
    container_name: foodservice
    depends_on:
      - mongo
      - rabbitmq

  basketservice:
    image: basketservice:latest
    build:
      context: .
      dockerfile: src/services/BasketService/Dockerfile
    container_name: basketservice
    depends_on:
      - mongo
      - rabbitmq

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: src/services/NotificationService/Dockerfile
    container_name: notificationservice
    depends_on:
      - mongo
      - rabbitmq

  userservice:
    image: userservice:latest
    build:
      context: .
      dockerfile: src/services/UserService/Dockerfile
    container_name: userservice
    depends_on:
      - mongo
      - rabbitmq