version: '3.4'

services:

  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: src/gateways/API.Gateway/Dockerfile
    container_name: apigateway

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul

  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongo

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672

  firstservice:
    image: firstservice:latest
    build:
      context: .
      dockerfile: src/services/FirstService/Dockerfile
    container_name: firstservice

  secondservice:
    image: secondservice:latest
    build:
      context: .
      dockerfile: src/services/SecondService/Dockerfile
    container_name: secondservice
    depends_on:
      - mongo

  thirdservice:
    image: thirdservice:latest
    build:
      context: .
      dockerfile: src/services/ThirdService/Dockerfile
    container_name: thirdservice
    depends_on:
      - redis
      - rabbitmq

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: src/services/NotificationService/Dockerfile
    container_name: notificationservice
    depends_on:
      - mongo
      - rabbitmq