version: '3.4'

services:
  firstservice:
    image: ${DOCKER_REGISTRY-}firstservice
    build:
      context: .
      dockerfile:FirstService/Dockerfile
    container_name: firstservice

  secondservice:
    image: ${DOCKER_REGISTRY-}secondservice
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    container_name: secondservice

  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: src/gateways/API.Gateway/Dockerfile
    container_name: apigateway