version: '3.4'

services:

  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://localhost:54140
    ports:
      - "4200:80"

  consul:
    ports:
      - "5013:8500"

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

  mongo-express:
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44393
    ports:
      - "60604:80"
      - "44393:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  medicalservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://medicalservice:80
      - ServiceConfig__serviceName=medicalservice
      - ServiceConfig__serviceId=medicalservice-v1
      - MongoDB__Host=mongo
    ports:
      - "54140:80"

  foodservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://foodservice:80
      - ServiceConfig__serviceName=foodservice
      - ServiceConfig__serviceId=foodservice-v1
      - MongoDB__Host=mongo
    ports:
      - "54150:80"

  basketservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://basketservice:80
      - ServiceConfig__serviceName=basketservice
      - ServiceConfig__serviceId=basketservice-v1
      - MongoDB__Host=mongo
    ports:
      - "54160:80"

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://notificationservice:80
      - ServiceConfig__serviceName=notificationservice
      - ServiceConfig__serviceId=notificationservice-v1
      - MongoDB__Host=mongo
    ports:
      - "54170:80"

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://userservice:80
      - ServiceConfig__serviceName=userservice
      - ServiceConfig__serviceId=userservice-v1
      - MongoDB__Host=mongo
    ports:
      - "54180:80"

volumes:
    mongodb_data_volume:
      external: true
    rabbitmq:
      driver: local